spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bryce_generator
    username: postgres
    password: postgres
