# 服务
server:
  port: 8100

# Spring 配置
spring:
  profiles:
    active: mysql

# Mybatis Plus 配置
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置
bryce:
  generator:
    table-prefix: brc_
    package-name: com.brycehan.boot

# 日志
#logging:
#  level:
#    com.brycehan.generator: debug
#    web: debug
